### ISSUE TITLE
Confirmation: .ckan file in mod root

### ISSUE THREAD

**Issue by OrbitalManeuvers** [zorg2044/BoringCrewServices#55]
Out of hundreds of mods I have and use regularly and in my downloads folder, I have only two that contain a .ckan file in the root of the mod - this one and KSPCommunityPartModules. 

Just making sure this is on purpose.

Brought to you by Details At The End Nitpickery headspace.

**Comment by zorg2044** [comment]
I'm told its in the right place.

**Comment by SofieBrink** [comment]
Thought I’d also just respond for a bit more clarity.
It is infact correct, the the fact you haven’t seen it before is likely because very few mods maintain their own .ckan file. Even though it has significant advantages, most mods existed before internal ckan files were supported, or authors are simply not aware of them.

hope that explains it a bit!

**Comment by OrbitalManeuvers** [comment]
yeah makes sense. will you have a .version file?
